import { Pool } from "pg";
import type { ActivityEvent, DoorAction, DoorState, GarageCommand, GarageStatus, LatestCamera, MqttStateMessage, MqttTelemetryMessage } from "@garage-control/shared-types";
import type { CommandRecord, Repository, UserRecord } from "./repository.js";

type Row = Record<string, unknown>;
const iso = (value: unknown): string | null => value instanceof Date ? value.toISOString() : typeof value === "string" ? value : null;
const asStatus = (row: Row, deviceId: string): GarageStatus => ({
  state: (row.state as DoorState | undefined) ?? "UNKNOWN", lastChangedAt: iso(row.last_changed_at), requestedAction: (row.requested_action as DoorAction | null | undefined) ?? null,
  device: { deviceId, online: row.online === true, lastSeen: iso(row.last_seen), rssi: typeof row.rssi === "number" ? row.rssi : null, uptimeSeconds: typeof row.uptime_seconds === "number" ? row.uptime_seconds : null, sensors: { closed: row.closed_sensor === true, open: row.open_sensor === true, ...(row.obstruction_sensor === null || row.obstruction_sensor === undefined ? {} : { obstruction: row.obstruction_sensor === true }) }, firmwareVersion: typeof row.firmware_version === "string" ? row.firmware_version : null }
});

export class PostgresRepository implements Repository {
  readonly pool: Pool;
  constructor(databaseUrl: string) { this.pool = new Pool({ connectionString: databaseUrl, max: 10, application_name: "garage-control-api" }); }
  async getGarageStatus(): Promise<GarageStatus> {
    const result = await this.pool.query("SELECT gs.*, d.online, d.last_seen, d.rssi, d.uptime_seconds, d.firmware_version FROM garage_state gs JOIN devices d ON d.id = gs.device_id ORDER BY gs.updated_at DESC LIMIT 1");
    return result.rows[0] ? asStatus(result.rows[0] as Row, String(result.rows[0].device_id)) : asStatus({}, "unregistered");
  }
  async findUserByEmail(email: string): Promise<UserRecord | null> { const result = await this.pool.query("SELECT id, email, password_hash, role FROM users WHERE email = $1", [email]); const row = result.rows[0] as Row | undefined; return row ? { id: String(row.id), email: String(row.email), passwordHash: String(row.password_hash), role: row.role === "owner" ? "owner" : "operator" } : null; }
  async findCommand(commandId: string): Promise<CommandRecord | null> { const result = await this.pool.query("SELECT command_id, action, created_at, device_id, status, result FROM commands WHERE command_id = $1", [commandId]); const row = result.rows[0] as Row | undefined; return row ? { commandId: String(row.command_id), action: String(row.action) as DoorAction, timestamp: String(row.created_at instanceof Date ? row.created_at.toISOString() : row.created_at), deviceId: String(row.device_id), status: String(row.status) as CommandRecord["status"], result: row.result ? String(row.result) : null } : null; }
  async createCommand(command: GarageCommand): Promise<CommandRecord> { const result = await this.pool.query("INSERT INTO commands (command_id, device_id, action, created_at, status) VALUES ($1, $2, $3, $4, 'PENDING') RETURNING command_id, action, created_at, device_id, status, result", [command.commandId, command.deviceId, command.action, command.timestamp]); return (await this.findCommand(String(result.rows[0].command_id))) as CommandRecord; }
  async updateCommand(commandId: string, patch: Partial<Pick<CommandRecord, "status" | "result">>): Promise<CommandRecord | null> { await this.pool.query("UPDATE commands SET status = COALESCE($2, status), result = COALESCE($3, result), updated_at = now() WHERE command_id = $1", [commandId, patch.status ?? null, patch.result ?? null]); return this.findCommand(commandId); }
  async applyState(message: MqttStateMessage): Promise<GarageStatus> {
    await this.pool.query("INSERT INTO devices (id, kind, online, last_seen, firmware_version) VALUES ($1, 'controller', true, $2, $3) ON CONFLICT (id) DO UPDATE SET online = true, last_seen = EXCLUDED.last_seen, firmware_version = EXCLUDED.firmware_version", [message.deviceId, message.timestamp, message.firmwareVersion]);
    await this.pool.query("INSERT INTO garage_state (device_id, state, closed_sensor, open_sensor, requested_action, last_changed_at) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (device_id) DO UPDATE SET state = EXCLUDED.state, closed_sensor = EXCLUDED.closed_sensor, open_sensor = EXCLUDED.open_sensor, requested_action = EXCLUDED.requested_action, last_changed_at = CASE WHEN garage_state.state <> EXCLUDED.state THEN EXCLUDED.last_changed_at ELSE garage_state.last_changed_at END, updated_at = now()", [message.deviceId, message.state, message.sensors.closed, message.sensors.open, message.requestedAction ?? null, message.timestamp]);
    return this.getGarageStatus();
  }
  async applyTelemetry(message: MqttTelemetryMessage): Promise<GarageStatus> { await this.pool.query("UPDATE devices SET online = true, last_seen = $2, rssi = $3, uptime_seconds = $4, firmware_version = $5 WHERE id = $1", [message.deviceId, message.timestamp, message.rssi, message.uptimeSeconds, message.firmwareVersion]); return this.getGarageStatus(); }
  async markOffline(deviceId: string): Promise<GarageStatus> { await this.pool.query("UPDATE devices SET online = false WHERE id = $1", [deviceId]); return this.getGarageStatus(); }
  async addEvent(type: ActivityEvent["type"], detail: string, imageId?: string): Promise<ActivityEvent> { const result = await this.pool.query("INSERT INTO garage_events (type, detail, image_id) VALUES ($1, $2, $3) RETURNING id, type, created_at, detail, image_id", [type, detail, imageId ?? null]); const row = result.rows[0] as Row; return { id: String(row.id), type: String(row.type) as ActivityEvent["type"], createdAt: String((row.created_at as Date).toISOString()), detail: String(row.detail), ...(row.image_id ? { imageId: String(row.image_id) } : {}) }; }
  async listEvents(limit: number, type?: ActivityEvent["type"]): Promise<ActivityEvent[]> { const result = type ? await this.pool.query("SELECT id, type, created_at, detail, image_id FROM garage_events WHERE type = $2 ORDER BY created_at DESC LIMIT $1", [limit, type]) : await this.pool.query("SELECT id, type, created_at, detail, image_id FROM garage_events ORDER BY created_at DESC LIMIT $1", [limit]); return result.rows.map((row: Row) => ({ id: String(row.id), type: String(row.type) as ActivityEvent["type"], createdAt: String((row.created_at as Date).toISOString()), detail: String(row.detail), ...(row.image_id ? { imageId: String(row.image_id) } : {}) })); }
  async getLatestCamera(): Promise<LatestCamera | null> { const result = await this.pool.query("SELECT id, camera_id, captured_at, reason, public_url FROM camera_images ORDER BY captured_at DESC LIMIT 1"); const row = result.rows[0] as Row | undefined; return row ? { id: String(row.id), cameraId: String(row.camera_id), capturedAt: String((row.captured_at as Date).toISOString()), reason: String(row.reason) as LatestCamera["reason"], url: String(row.public_url) } : null; }
  // id is passed twice (id uuid, storage_key text): one shared $1 cannot be both types.
  async saveCameraImage(input: { id: string; cameraId: string; capturedAt: string; reason: LatestCamera["reason"]; url: string }): Promise<LatestCamera> { await this.pool.query("INSERT INTO camera_images (id, camera_id, captured_at, reason, storage_key, public_url) VALUES ($1, $2, $3, $4, $5, $6)", [input.id, input.cameraId, input.capturedAt, input.reason, input.id, input.url]); return input; }
  async close(): Promise<void> { await this.pool.end(); }
}
