persistence true
persistence_location /mosquitto/data/
log_dest stdout
listener 8883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwords
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false
use_identity_as_username false
max_inflight_messages 20
message_size_limit 65536
